import type { CardData } from "../types/CardTypes";

export const CARD_DATABASE: Record<string, CardData> = {
  SENTINEL_01: {
    id: "SENTINEL_01",
    type: "MONSTER",
    nameKey: "Sentinela de Ferro",
    descriptionKey: "Um guardião ancestral que nunca dorme.",
    manaCost: 3,
    atk: 15,
    def: 20,
    imageKey: "monster_sentinel",
    width: 300,
    height: 400,
  },
  SENTINEL_02: {
    id: "SENTINEL_02",
    type: "EFFECT_MONSTER",
    nameKey: "Sentinela de Ferro",
    descriptionKey: "Um guardião ancestral que nunca dorme.",
    manaCost: 3,
    atk: 12,
    def: 20,
    imageKey: "monster_sentinel",
    width: 300,
    height: 400,
  },
  FIRE_BALL: {
    id: "FIRE_BALL",
    type: "SPELL",
    nameKey: "Bola de Fogo",
    descriptionKey: "Causa 10 de dano a todos os inimigos.",
    effects: { type: "BURN", value: 10, targetSide: "OPPONENT" },
    manaCost: 2,
    imageKey: "spell_fireball",
    width: 300,
    height: 400,
  },
  DRAW_CARD: {
    id: "DRAW_CARD",
    type: "SPELL",
    nameKey: "Pote da ganância",
    descriptionKey: "Compre 1 carta.",
    effects: { type: "DRAW_CARDS", value: 1, targetSide: "OWNER" },
    manaCost: 2,
    imageKey: "spell_fireball",
    width: 300,
    height: 400,
  },
  DARK_TRAP: {
    id: "DARK_TRAP",
    type: "TRAP",
    nameKey: "Armadilha Sombria",
    descriptionKey: "Imobiliza o próximo monstro atacante.",
    manaCost: 1,
    imageKey: "trap_darkness",
    width: 300,
    height: 400,
  },
};
