import type { CardData } from "../types/CardTypes";

export const CARD_DATABASE: Record<string, CardData> = {
  SENTINEL_01: {
    id: "SENTINEL_01",
    type: "MONSTER",
    nameKey: "Sentinela de Ferro",
    descriptionKey: "Um guardião ancestral que nunca dorme.",
    manaCost: 2,
    atk: 40,
    def: 55,
    imageKey: "",
    width: 300,
    height: 400,
  },
  SENTINEL_02: {
    id: "SENTINEL_02",
    type: "EFFECT_MONSTER",
    nameKey: "Sentinela de Ferro",
    descriptionKey: "Um guardião ancestral que nunca dorme.",
    manaCost: 2,
    atk: 35,
    def: 45,
    imageKey: "",
    width: 300,
    height: 400,
  },
  FIRE_BALL: {
    id: "FIRE_BALL",
    type: "SPELL",
    nameKey: "Bola de Fogo",
    descriptionKey: "Causa 30 de dano a todos os inimigos.",
    effects: { type: "BURN", value: 30, targetSide: "OPPONENT" },
    manaCost: 2,
    imageKey: "",
    width: 300,
    height: 400,
  },
  DRAW_CARD: {
    id: "DRAW_CARD",
    type: "SPELL",
    nameKey: "Pote da ganância",
    descriptionKey: "Compre 1 carta.",
    effects: { type: "DRAW_CARD", value: 1, targetSide: "OWNER" },
    manaCost: 2,
    imageKey: "",
    width: 300,
    height: 400,
  },
  CHANGE_POS: {
    id: "CHANGE_POS",
    type: "SPELL",
    nameKey: "Virada de jogo",
    descriptionKey: "Escolha um monstro no campo. Mude a posição do alvo",
    effects: { type: "CHANGE_POS", targetSide: "OPPONENT" },
    manaCost: 1,
    imageKey: "",
    width: 300,
    height: 400,
  },
  DESTROY_SPELL: {
    id: "DESTROY_SPELL",
    type: "SPELL",
    nameKey: "Tornado",
    descriptionKey: "Escolha uma magia no campo, destrua a carta",
    effects: { type: "DESTROY", targetSide: "OPPONENT", targetType: "SPELL" },
    manaCost: 1,
    imageKey: "",
    width: 300,
    height: 400,
  },
  BOOST_ATK: {
    id: "BOOST_ATK",
    type: "SPELL",
    nameKey: "Fúria",
    descriptionKey: "Aumente o ataque do monstro em 15 pontos.",
    effects: { type: "BOOST_ATK", value: 15, targetSide: "BOTH" },
    manaCost: 1,
    imageKey: "",
    width: 300,
    height: 400,
  },
  BOOST_DEF: {
    id: "BOOST_DEF",
    type: "SPELL",
    nameKey: "Escudo",
    descriptionKey: "Aumente a defesa do monstro em 15 pontos.",
    effects: { type: "BOOST_DEF", value: 15, targetSide: "BOTH" },
    manaCost: 1,
    imageKey: "spell_fireball",
    width: 300,
    height: 400,
  },
  REVIVE_SPELL: {
    id: "REVIVE_SPELL",
    type: "SPELL",
    nameKey: "Reviver magia",
    descriptionKey:
      "Restaure uma carta mágica do seu cemitério, devolva-a pra sua mão.",
    effects: { type: "REVIVE", targetSide: "OWNER" },
    manaCost: 1,
    imageKey: "spell_fireball",
    width: 300,
    height: 400,
  },
  REVIVE_MONSTER: {
    id: "REVIVE_MONSTER",
    type: "SPELL",
    nameKey: "Reviver monstro",
    descriptionKey: "Revive um monstro do cemitério e o envia ao campo.",
    effects: { type: "REVIVE", targetSide: "BOTH", targetType: "MONSTER" },
    manaCost: 1,
    imageKey: "",
    width: 300,
    height: 400,
  },
  NERF_ATK: {
    id: "NERF_ATK",
    type: "SPELL",
    nameKey: "Memento",
    descriptionKey: "Diminua o ataque do monstro em 15 pontos.",
    effects: { type: "NERF_ATK", value: 15, targetSide: "BOTH" },
    manaCost: 1,
    imageKey: "",
    width: 300,
    height: 400,
  },
  BOUNCE: {
    id: "BOUNCE",
    type: "SPELL",
    nameKey: "Alavanca",
    descriptionKey: "Selecione um monstro no campo. Retorne o alvo à mão.",
    effects: { type: "BOUNCE", targetSide: "OPPONENT", targetType: "MONSTER" },
    manaCost: 1,
    imageKey: "",
    width: 300,
    height: 400,
  },
  DARK_TRAP: {
    id: "DARK_TRAP",
    type: "TRAP",
    nameKey: "Armadilha Sombria",
    descriptionKey: "Destrua um monstro em campo do seu oponente.",
    effects: { type: "DESTROY", targetSide: "OPPONENT", targetType: "MONSTER" },
    manaCost: 1,
    imageKey: "",
    width: 300,
    height: 400,
  },
  TOON_KNIGHT: {
    id: "TOON_KNIGHT",
    type: "MONSTER",
    nameKey: "Cavaleiro Toon",
    descriptionKey: "Um guerreiro de papel com coragem de aço.",
    manaCost: 2,
    atk: 50,
    def: 40,
    imageKey: "warrior1_example", // Use as chaves do seu Assets Pack
    width: 300,
    height: 400,
  },
  MAGE_APPRENTICE: {
    id: "MAGE_APPRENTICE",
    type: "EFFECT_MONSTER",
    nameKey: "Aprendiz de Mago",
    descriptionKey:
      "Diz a lenda que ele ainda está aprendendo a não explodir coisas.",
    manaCost: 1,
    atk: 35,
    def: 60,
    imageKey: "warrior2_example",
    width: 300,
    height: 400,
  },
  BANDIT_ARCHER: {
    id: "BANDIT_ARCHER",
    type: "EFFECT_MONSTER",
    nameKey: "Bandido arqueiro",
    descriptionKey: "Diz a lenda que ele se inspira em algum 'Wood'.",
    manaCost: 1,
    atk: 52,
    def: 20,
    imageKey: "warrior2_example",
    width: 300,
    height: 400,
  },
  POT_OF_LUCK: {
    id: "POT_OF_LUCK",
    type: "SPELL",
    nameKey: "Pote da Sorte",
    descriptionKey: "A sorte favorece os audazes. Compre 2 cartas.",
    effects: { type: "DRAW_CARD", value: 2, targetSide: "OWNER" },
    manaCost: 2,
    imageKey: "revive_example",
    width: 300,
    height: 400,
  },
  REGEN_FLOWER: {
    id: "REGEN_FLOWER",
    type: "SPELL",
    nameKey: "Flor da Vida",
    descriptionKey: "Um aroma doce que cura suas feridas. +40 LP.",
    effects: { type: "HEAL", value: 40, targetSide: "OWNER" },
    manaCost: 1,
    imageKey: "buff_example",
    width: 300,
    height: 400,
  },
  MANA_CRYSTAL: {
    id: "MANA_CRYSTAL",
    type: "SPELL",
    nameKey: "Cristal de Mana",
    descriptionKey: "Energia pura canalizada. Ganhe 2 de mana.",
    effects: { type: "GAIN_MANA", value: 2, targetSide: "OWNER" },
    manaCost: 0,
    imageKey: "twister_example",
    width: 300,
    height: 400,
  },
  ICE_SHIELD: {
    id: "ICE_SHIELD",
    type: "SPELL",
    nameKey: "Escudo de Gelo",
    descriptionKey: "Aumente a defesa de um monstro em 30 pontos.",
    effects: { type: "BOOST_DEF", value: 30, targetSide: "BOTH" },
    manaCost: 1,
    imageKey: "buff_example",
    width: 300,
    height: 400,
  },
  REVERSE_TRAP: {
    id: "REVERSE_TRAP",
    type: "TRAP",
    nameKey: "Contra-Ataque",
    descriptionKey: "Reduz o ataque de um monstro inimigo em 20.",
    effects: { type: "NERF_ATK", value: 20, targetSide: "OPPONENT" },
    manaCost: 1,
    imageKey: "revive_example",
    width: 300,
    height: 400,
  },
};
